export const SEAT_STATUS = Object.freeze({
	AVAILABLE: "available",
	RESERVED: "reserved",
	SOLD: "sold",
	BLOCKED: "blocked",
	SELECTED: "selected",
});

export const DEFAULT_SEAT_PRICE = 18;
export const MAX_SEAT_SELECTION = 6;

export const PRICING_RULES = Object.freeze({
	CONVENIENCE_FEE_PER_SEAT: 1.75,
	ORDER_PROCESSING_FEE: 2.5,
	TAX_RATE: 0.18,
});

export const SEAT_CLASS = Object.freeze({
	STANDARD: "standard",
	PRIME: "prime",
	RECLINER: "recliner",
});

export const SEAT_CLASS_DETAILS = Object.freeze({
	[SEAT_CLASS.STANDARD]: Object.freeze({
		label: "Standard",
		price: 14,
	}),
	[SEAT_CLASS.PRIME]: Object.freeze({
		label: "Prime",
		price: 18,
	}),
	[SEAT_CLASS.RECLINER]: Object.freeze({
		label: "Recliner",
		price: 24,
	}),
});

export function resolveSeatClassByRow(rowNumber) {
	if (rowNumber >= 9) {
		return SEAT_CLASS.RECLINER;
	}

	if (rowNumber >= 5) {
		return SEAT_CLASS.PRIME;
	}

	return SEAT_CLASS.STANDARD;
}

export const SEAT_LAYOUT_TEMPLATE = [
	{
		rowNumber: 1,
		left: [
			SEAT_STATUS.AVAILABLE,
			SEAT_STATUS.AVAILABLE,
			SEAT_STATUS.AVAILABLE,
			SEAT_STATUS.AVAILABLE,
		],
		right: [
			SEAT_STATUS.AVAILABLE,
			SEAT_STATUS.AVAILABLE,
			SEAT_STATUS.AVAILABLE,
			SEAT_STATUS.AVAILABLE,
		],
	},
	{
		rowNumber: 2,
		left: [
			SEAT_STATUS.AVAILABLE,
			SEAT_STATUS.AVAILABLE,
			SEAT_STATUS.AVAILABLE,
			SEAT_STATUS.AVAILABLE,
			SEAT_STATUS.SOLD,
		],
		right: [
			SEAT_STATUS.BLOCKED,
			SEAT_STATUS.AVAILABLE,
			SEAT_STATUS.AVAILABLE,
			SEAT_STATUS.AVAILABLE,
			SEAT_STATUS.AVAILABLE,
		],
	},
	{
		rowNumber: 3,
		left: [
			SEAT_STATUS.AVAILABLE,
			SEAT_STATUS.AVAILABLE,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.AVAILABLE,
			SEAT_STATUS.SOLD,
			SEAT_STATUS.BLOCKED,
		],
		right: [
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.SOLD,
			SEAT_STATUS.AVAILABLE,
			SEAT_STATUS.AVAILABLE,
			SEAT_STATUS.AVAILABLE,
			SEAT_STATUS.AVAILABLE,
		],
	},
	{
		rowNumber: 4,
		left: [
			SEAT_STATUS.AVAILABLE,
			SEAT_STATUS.AVAILABLE,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
		],
		right: [
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.AVAILABLE,
		],
	},
	{
		rowNumber: 5,
		left: [
			SEAT_STATUS.AVAILABLE,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
		],
		right: [
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.AVAILABLE,
			SEAT_STATUS.AVAILABLE,
		],
	},
	{
		rowNumber: 6,
		left: [
			SEAT_STATUS.AVAILABLE,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
		],
		right: [
			SEAT_STATUS.SELECTED,
			SEAT_STATUS.SELECTED,
			SEAT_STATUS.BLOCKED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.AVAILABLE,
		],
	},
	{
		rowNumber: 7,
		left: [
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
		],
		right: [
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
		],
	},
	{
		rowNumber: 8,
		left: [
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.AVAILABLE,
			SEAT_STATUS.AVAILABLE,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
		],
		right: [
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.AVAILABLE,
		],
	},
	{
		rowNumber: 9,
		left: [
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
		],
		right: [
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.AVAILABLE,
			SEAT_STATUS.AVAILABLE,
			SEAT_STATUS.AVAILABLE,
		],
	},
	{
		rowNumber: 10,
		left: [
			SEAT_STATUS.AVAILABLE,
			SEAT_STATUS.AVAILABLE,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
		],
		right: [
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.RESERVED,
			SEAT_STATUS.AVAILABLE,
			SEAT_STATUS.AVAILABLE,
			SEAT_STATUS.AVAILABLE,
		],
	},
];
